---
- name: restart server
  service:
    name: 'openvpn'
    arguments: '{{ openvpn_server_daemon }}'
    state: restarted

- name: restart client
  delegate_to: '{{ openvpn_client }}'
  service:
    name: 'openvpn'
    arguments: '{{ openvpn_client_daemon }}'
    state: restarted
